const { writeFileSync, existsSync, mkdirSync } = require('fs');
const { spawnSync } = require('child_process');
const path = require('path');

const env_file = ``; //
SESSION_ID="INCONNU~XD~2UkSgCKQ#f2QIZ-7TlhTiz_KdyINcTzwn1bIdf33C4scZZIvL-y4"
PREFIX=¬∑
OWNER_NUMBER=50946062382
SUDO_NUMBER=50946062382
OWNER_NAME=‚Äéüòà‚ò†Ô∏èƒ§ Œ≤ÂçÇÂá†‰∏Çƒ§‰πá‰πá ·ó™üòà‚ò†Ô∏è 
AUTO_STATUS_SEEN=false
AUTO_BIO=false
AUTO_STATUS_REACT=false
AUTO_READ=false
AUTO_RECORDING=false
AUTO_REACT=false
STATUS_READ_MSG=STATUS VIEWED BY INCONNU XD V2 ‚úÖ
ANTILINK=true
ANTIBOT=true
ANTIBOT_WARNINGS=3
REJECT_CALL=false
NOT_ALLOW=true
AUTO_STATUS_REACT=false
MODE=private
WELCOME=true 

if (!env_file.trim()) {
  console.error("Aucune donn√©e de configuration dans 'env_file'. Remplissez les infos.");
  process.exit(1);
}

const envPath = path.join(__dirname, 'ovl', '.env');

function runCommand(command, args, options = {}) {
  const result = spawnSync(command, args, { stdio: 'inherit', ...options });
  if (result.error || result.status !== 0) {
    throw new Error(`Erreur lors de l'ex√©cution : ${command} ${args.join(' ')}`);
  }
}

if (!existsSync('ovl')) {
  console.log("Clonage...");
  runCommand('git', ['clone', 'https://github.com/Ainz-devs/OVL-MD-V2', 'ovl']);
  runCommand('npm', ['install'], { cwd: 'ovl' });
}

if (!existsSync(envPath)) {
  mkdirSync(path.dirname(envPath), { recursive: true });
  writeFileSync(envPath, env_file.trim());
}

runCommand('npm', ['run', 'Ovl'], { cwd: 'ovl' });
